/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EncryptedGradeRecord__factory } from "./EncryptedGradeRecord__factory";
export { FHECounter__factory } from "./FHECounter__factory";
