/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedGradeRecordInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deleteGrade"
      | "entryCount"
      | "getEncryptedGlobalStats"
      | "getEncryptedScore"
      | "getEncryptedStudentStats"
      | "getEntry"
      | "getEntryCount"
      | "getGlobalStats"
      | "getStudentEntries"
      | "getStudentEntryCount"
      | "getStudentStats"
      | "globalStatsCallback"
      | "gradeEntries"
      | "isGlobalStatsFinalized"
      | "isStudentStatsFinalized"
      | "protocolId"
      | "requestGlobalStats"
      | "requestStudentStats"
      | "studentEntries"
      | "studentEntryCount"
      | "studentStatsCallback"
      | "submitGrade"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GlobalStatsPublished"
      | "GlobalStatsRequested"
      | "GradeDeleted"
      | "GradeSubmitted"
      | "StudentStatsPublished"
      | "StudentStatsRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deleteGrade",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "entryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedStudentStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentEntries",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentEntryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "globalStatsCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "gradeEntries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isGlobalStatsFinalized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isStudentStatsFinalized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestStudentStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "studentEntries",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "studentEntryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "studentStatsCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitGrade",
    values: [BytesLike, BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "deleteGrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedStudentStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalStatsCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gradeEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGlobalStatsFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isStudentStatsFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestStudentStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentStatsCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitGrade",
    data: BytesLike
  ): Result;
}

export namespace GlobalStatsPublishedEvent {
  export type InputTuple = [
    averageScore: BigNumberish,
    totalCount: BigNumberish
  ];
  export type OutputTuple = [averageScore: bigint, totalCount: bigint];
  export interface OutputObject {
    averageScore: bigint;
    totalCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GlobalStatsRequestedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GradeDeletedEvent {
  export type InputTuple = [entryId: BigNumberish, student: AddressLike];
  export type OutputTuple = [entryId: bigint, student: string];
  export interface OutputObject {
    entryId: bigint;
    student: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GradeSubmittedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    student: AddressLike,
    subject: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    entryId: bigint,
    student: string,
    subject: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    entryId: bigint;
    student: string;
    subject: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StudentStatsPublishedEvent {
  export type InputTuple = [
    student: AddressLike,
    averageScore: BigNumberish,
    count: BigNumberish
  ];
  export type OutputTuple = [
    student: string,
    averageScore: bigint,
    count: bigint
  ];
  export interface OutputObject {
    student: string;
    averageScore: bigint;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StudentStatsRequestedEvent {
  export type InputTuple = [student: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [student: string, requestId: bigint];
  export interface OutputObject {
    student: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedGradeRecord extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedGradeRecord;
  waitForDeployment(): Promise<this>;

  interface: EncryptedGradeRecordInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deleteGrade: TypedContractMethod<
    [entryId: BigNumberish],
    [void],
    "nonpayable"
  >;

  entryCount: TypedContractMethod<[], [bigint], "view">;

  getEncryptedGlobalStats: TypedContractMethod<
    [],
    [[string, bigint] & { encryptedSum: string; count: bigint }],
    "view"
  >;

  getEncryptedScore: TypedContractMethod<
    [entryId: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedStudentStats: TypedContractMethod<
    [student: AddressLike],
    [[string, bigint] & { encryptedSum: string; count: bigint }],
    "view"
  >;

  getEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        student: string;
        subject: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getEntryCount: TypedContractMethod<[], [bigint], "view">;

  getGlobalStats: TypedContractMethod<
    [],
    [[bigint, bigint] & { averageScore: bigint; totalCount: bigint }],
    "view"
  >;

  getStudentEntries: TypedContractMethod<
    [student: AddressLike],
    [bigint[]],
    "view"
  >;

  getStudentEntryCount: TypedContractMethod<
    [student: AddressLike],
    [bigint],
    "view"
  >;

  getStudentStats: TypedContractMethod<
    [student: AddressLike],
    [[bigint, bigint] & { averageScore: bigint; count: bigint }],
    "view"
  >;

  globalStatsCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  gradeEntries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        student: string;
        subject: string;
        encryptedScore: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  isGlobalStatsFinalized: TypedContractMethod<[], [boolean], "view">;

  isStudentStatsFinalized: TypedContractMethod<
    [student: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestGlobalStats: TypedContractMethod<[], [void], "nonpayable">;

  requestStudentStats: TypedContractMethod<
    [student: AddressLike],
    [void],
    "nonpayable"
  >;

  studentEntries: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  studentEntryCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  studentStatsCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  submitGrade: TypedContractMethod<
    [encryptedScore: BytesLike, inputProof: BytesLike, subject: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deleteGrade"
  ): TypedContractMethod<[entryId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedGlobalStats"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { encryptedSum: string; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedScore"
  ): TypedContractMethod<[entryId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedStudentStats"
  ): TypedContractMethod<
    [student: AddressLike],
    [[string, bigint] & { encryptedSum: string; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [entryId: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        student: string;
        subject: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { averageScore: bigint; totalCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudentEntries"
  ): TypedContractMethod<[student: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getStudentEntryCount"
  ): TypedContractMethod<[student: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStudentStats"
  ): TypedContractMethod<
    [student: AddressLike],
    [[bigint, bigint] & { averageScore: bigint; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalStatsCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gradeEntries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        student: string;
        subject: string;
        encryptedScore: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isGlobalStatsFinalized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isStudentStatsFinalized"
  ): TypedContractMethod<[student: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestGlobalStats"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestStudentStats"
  ): TypedContractMethod<[student: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "studentEntries"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "studentEntryCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "studentStatsCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitGrade"
  ): TypedContractMethod<
    [encryptedScore: BytesLike, inputProof: BytesLike, subject: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GlobalStatsPublished"
  ): TypedContractEvent<
    GlobalStatsPublishedEvent.InputTuple,
    GlobalStatsPublishedEvent.OutputTuple,
    GlobalStatsPublishedEvent.OutputObject
  >;
  getEvent(
    key: "GlobalStatsRequested"
  ): TypedContractEvent<
    GlobalStatsRequestedEvent.InputTuple,
    GlobalStatsRequestedEvent.OutputTuple,
    GlobalStatsRequestedEvent.OutputObject
  >;
  getEvent(
    key: "GradeDeleted"
  ): TypedContractEvent<
    GradeDeletedEvent.InputTuple,
    GradeDeletedEvent.OutputTuple,
    GradeDeletedEvent.OutputObject
  >;
  getEvent(
    key: "GradeSubmitted"
  ): TypedContractEvent<
    GradeSubmittedEvent.InputTuple,
    GradeSubmittedEvent.OutputTuple,
    GradeSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "StudentStatsPublished"
  ): TypedContractEvent<
    StudentStatsPublishedEvent.InputTuple,
    StudentStatsPublishedEvent.OutputTuple,
    StudentStatsPublishedEvent.OutputObject
  >;
  getEvent(
    key: "StudentStatsRequested"
  ): TypedContractEvent<
    StudentStatsRequestedEvent.InputTuple,
    StudentStatsRequestedEvent.OutputTuple,
    StudentStatsRequestedEvent.OutputObject
  >;

  filters: {
    "GlobalStatsPublished(uint32,uint32)": TypedContractEvent<
      GlobalStatsPublishedEvent.InputTuple,
      GlobalStatsPublishedEvent.OutputTuple,
      GlobalStatsPublishedEvent.OutputObject
    >;
    GlobalStatsPublished: TypedContractEvent<
      GlobalStatsPublishedEvent.InputTuple,
      GlobalStatsPublishedEvent.OutputTuple,
      GlobalStatsPublishedEvent.OutputObject
    >;

    "GlobalStatsRequested(uint256)": TypedContractEvent<
      GlobalStatsRequestedEvent.InputTuple,
      GlobalStatsRequestedEvent.OutputTuple,
      GlobalStatsRequestedEvent.OutputObject
    >;
    GlobalStatsRequested: TypedContractEvent<
      GlobalStatsRequestedEvent.InputTuple,
      GlobalStatsRequestedEvent.OutputTuple,
      GlobalStatsRequestedEvent.OutputObject
    >;

    "GradeDeleted(uint256,address)": TypedContractEvent<
      GradeDeletedEvent.InputTuple,
      GradeDeletedEvent.OutputTuple,
      GradeDeletedEvent.OutputObject
    >;
    GradeDeleted: TypedContractEvent<
      GradeDeletedEvent.InputTuple,
      GradeDeletedEvent.OutputTuple,
      GradeDeletedEvent.OutputObject
    >;

    "GradeSubmitted(uint256,address,string,uint256)": TypedContractEvent<
      GradeSubmittedEvent.InputTuple,
      GradeSubmittedEvent.OutputTuple,
      GradeSubmittedEvent.OutputObject
    >;
    GradeSubmitted: TypedContractEvent<
      GradeSubmittedEvent.InputTuple,
      GradeSubmittedEvent.OutputTuple,
      GradeSubmittedEvent.OutputObject
    >;

    "StudentStatsPublished(address,uint32,uint32)": TypedContractEvent<
      StudentStatsPublishedEvent.InputTuple,
      StudentStatsPublishedEvent.OutputTuple,
      StudentStatsPublishedEvent.OutputObject
    >;
    StudentStatsPublished: TypedContractEvent<
      StudentStatsPublishedEvent.InputTuple,
      StudentStatsPublishedEvent.OutputTuple,
      StudentStatsPublishedEvent.OutputObject
    >;

    "StudentStatsRequested(address,uint256)": TypedContractEvent<
      StudentStatsRequestedEvent.InputTuple,
      StudentStatsRequestedEvent.OutputTuple,
      StudentStatsRequestedEvent.OutputObject
    >;
    StudentStatsRequested: TypedContractEvent<
      StudentStatsRequestedEvent.InputTuple,
      StudentStatsRequestedEvent.OutputTuple,
      StudentStatsRequestedEvent.OutputObject
    >;
  };
}
