/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EncryptedGradeRecord } from "./EncryptedGradeRecord";
export type { FHECounter } from "./FHECounter";
